### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ddugovic** [jpbberry/topgg-autoposter#3]
Is this software available under an free software license to execute, modify, and redistribute?  Thanks for your consideration.

**Comment by jpbberry** [comment]
I don't really mess with licenses I've no real clue, if you wanna yoink the code and use it, I don't mind, as for redistributing I'd rather you PR or something, but again there's no legal backing for it, do whatever you want I guess 😆

**Comment by ddugovic** [comment]
Thanks, I hadn't read carefully earlier but https://www.npmjs.com/package/topgg-autoposter indicates: "License ISC" whatever that means.

**Comment by jpbberry** [comment]
I think it's just the default when I ran `npm init`
