### ISSUE TITLE
Build Issue with TypeScript

### ISSUE THREAD

**Issue by CarelessInternet** [jpbberry/topgg-autoposter#5]
As I'm rebuilding my Discord bot from JavaScript to TypeScript, I seemed to get a build error every time:

```
node_modules/@top-gg/sdk/dist/structs/Webhook.d.ts:1:49 - error TS2307: Cannot find module 'express' or its corresponding type declarations.

1 import { Request, Response, NextFunction } from "express";
                                                  ~~~~~~~~~


Found 1 error.
```

I'm assuming it's due to `@top-gg/sdk` not being updated in `package.json`? I haven't manually installed `@top-gg/sdk` on my `package.json`, so it has to be this package. A pull request was merged to fix this error, and this package hasn't been updated to use the new version(s): https://github.com/top-gg/node-sdk/pull/56. Although I'm not sure if that is what's causing the error, it's the conclusion I have came to. As for now, I've downloaded the express types as a dev dependency, which solves the build issue.

**Comment by jpbberry** [comment]
This was finally fixed with the release of the new @top-gg/sdk version.
